language: julia

os:
    - linux
    - windows
    - osx

julia:
    - 1.0
    - 1.2
    - 1.3

jobs:
    include:
        - stage: "Documentation"
          os: linux
          script:
            - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
            - julia --project=docs/ docs/make.jl
          after_success:
            - julia --project=docs/ docs/deploy.jl

after_success:
    - julia -e 'cd(Pkg.dir("FEMQuad")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
